config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :new, :create, :destroy], param: :id do
      resources :comments, only: [:new, :create, :destroy]
      resources :likes, only: [:create]
    end
  end
  root 'pages#hello'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    can :read, Post

    return unless user.present?

    can :manage, Post, author_id: user.id
    can :manage, Comment, author_id: user.id

    return unless user.role == 'admin'

    can :manage, :all
    # Define abilities for the user here. For example:
    #
    #   return unless user.present?
    #   can :read, :all
    #   return unless user.admin?
    #   can :manage, :all
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, published: true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/blob/develop/docs/define_check_abilities.md
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  belongs_to :post, class_name: 'Post', foreign_key: 'post_id'

  private

  def update_post_comments_counter
    post.update(commentsCounter: post.comments.count)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  belongs_to :post, class_name: 'Post', foreign_key: 'post_id'

  after_create :update_likes_counter

  def update_likes_counter
    post.update(likesCounter: post.likes.count)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  has_many :comments, class_name: 'Comment', foreign_key: 'post_id', dependent: :destroy
  has_many :likes, class_name: 'Like', foreign_key: 'post_id', dependent: :destroy

  validates :title, :text, presence: true

  def recentcomments
    comments.order(created_at: :desc).limit(5)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  has_many :posts, class_name: 'Post', foreign_key: 'author_id', dependent: :destroy
  has_many :comments, class_name: 'Comment', foreign_key: 'author_id', dependent: :destroy
  has_many :likes, class_name: 'Like', foreign_key: 'author_id', dependent: :destroy

  validates :name, presence: true
  validates :email, presence: true
  validates :encrypted_password, presence: true
  # validates :postsCounter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def recentposts
    posts.order(created_at: :desc).limit(3)
  end

  # User::Roles
  # The available roles
  ROLES = %w[admin].freeze

  ROLES.each do |exact_role|
    define_method "#{exact_role}?" do
      role == exact_role
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :update_allowed_parameters, if: :devise_controller?

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password) }
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password) }
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  load_and_authorize_resource
  def new
    @comment = Comment.new
  end

  def create
    post = Post.find(params[:post_id])
    @comment = post.comments.create(comment_params)
    current_user = User.find(params[:user_id])
    @comment.author = current_user

    if @comment.save
      redirect_to user_post_path(params[:user_id], post)
      flash[:notice] = 'success'
    else
      flash.now[:error] = 'Error'
      render 'new'
    end
  end

  def destroy
    @user = User.find(params[:user_id])
    @post = Post.find_by!(id: params[:post_id])
    comment = Comment.find_by!(post_id: params[:post_id], id: params[:id])
    comment.destroy
    @post.decrement!(:commentsCounter)
    flash[:notice] = 'The comment was deleted'
    redirect_to user_post_path(@user, @post)
  end

  private

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    post = Post.find(params[:post_id])
    user = User.find(params[:user_id])
    like = Like.create(post:, author: user)

    if like.save
      redirect_to user_post_path(post.author, post), notice: 'liked!'
    else
      redirect_to user_post_path(post.author, post), alert: 'not liked.'
    end
  end

  def destroy
    post = Post.find(params[:post_id])
    like = Like.find_by(post:, user:)

    if like.destroy
      redirect_to user_post_path(post.author, post), notice: 'unliked!'
    else
      redirect_to user_post_path(post.author, post), alert: 'not unliked.'
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def hello; end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  load_and_authorize_resource
  before_action :set_user, only: %i[index show]

  def index
    @posts = @user.posts.includes(:comments)
    @like = @user.likes.new
  end

  def show
    @post = Post.find_by!(id: params[:id], author_id: @user.id)
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.new(post_params)

    if @post.save
      redirect_to user_post_path(@post.author, @post)
    else
      render :new
    end
  end

  def destroy
    current_user = User.find(params[:user_id])
    post = Post.find_by!(id: params[:id])
    post.destroy
    current_user.decrement!(:postsCounter)
    flash[:notice] = 'The post was deleted'
    redirect_to user_posts_path(current_user)
  end

  private

  def post_params
    params.require(:new_post).permit(:title, :text)
  end

  def set_user
    @user = User.find(params[:user_id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[show]

  def index
    @users = User.all
  end

  def show; end

  private

  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
<div id="<%= dom_id comment %>">
  <p>
    <strong><%= comment.author.name %>:</strong>
    <%= comment.text %>
  </p>

<% if can? :destroy, comment %>
  <%= button_to "Delete Comment", user_post_comment_path(comment.post.author, comment.post, comment), method: :delete %>
<% end %>
</div>

app/views/comments/new.html.erb
<h1 class="comment-form-heading">Add new comments</h1>

<%= form_with model: @comment, url: user_post_comments_path, method: :post, local: true, scope: :comment, class: "comment-form" do |form| %>
  <div>
    <%= form.label :text, class: "comment-form-label" %><br>
    <%= form.text_area :text, class: "comment-form-textarea" %>
  </div>
  <%= form.submit "Add Comment", class: "comment-form-submit" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
   <p class="notice"><%= notice %></p>        
   <p class="alert"><%= alert %></p>

    <%= yield %>
  </body>
</html>

app/views/pages/hello.html.erb
<h1>hellow world</h1>

  <% if user_signed_in? %>
    <%= button_to "Sign out", destroy_user_session_path, method: :delete, class: "devise-button" %>
  <% else %>
  <button class="devise-button">
    <%= link_to "Log in", new_user_session_path, class: "link-login"%>
  </button>
  <% end %>

app/views/posts/_post.html.erb
<div class="post_col", id="<%= dom_id post %>">
  <p>
    <%= post.text %>
  </p>

<div class="post_info">
  <p>
    <strong>Comments:</strong>
    <%= post.commentsCounter %>
  </p>

  <p>
    <strong>Likes:</strong>
    <%= post.likesCounter %>
  </p>

       <% if can? :destroy, post %>
        <%=button_to "Delete Post", user_post_path(@user, post), method: :delete %>
       <% end %>
</div>
</div>

app/views/posts/index.html.erb
<div id="users" class="container">
  <%= render @user %>
  <div class="post_container">
    <% @posts.each_with_index do |post, index| %>
    <%= link_to user_post_path(@user, post), class: "post_row" do %>
      <p> <%= post.title %> </p>
      <%= render post %>
    <% end %>
      <div class="comment_container">
        <% post.recentcomments.each do |comment| %>
          <div class="comment_row">
            <%= render comment %>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/posts/new.html.erb
<%= form_with model: @post, url: user_posts_path, method: :post, local: true, scope: :new_post, class: "post-form" do |form| %>
  <div>
    <%= form.label :title, class: "post-form-label" %><br>
    <%= form.text_field :title, class: "post-form-input" %>
  </div>

  <div>
    <%= form.label :text, class: "post-form-label" %><br>
    <%= form.text_area :text, class: "post-form-textarea" %>
  </div>
  <%= form.submit "Add Post", class: "post-form-submit" %>
<% end %>

app/views/posts/show.html.erb
<div class="container">

<div class="body_container">
<div class="header">

  <h1>
<%= @post.title + ' by ' + @user.name %>
  </h1>

<div class="post_info">
  <%= form_with model: @like, url: user_post_likes_path(user_id: @post.author.id, post_id: @post.id), local: true do |form| %>
    <%= form.submit "Add a like", class: "add-like" %>
  <% end %>
  <button type="button"><%= link_to "Add a comment", new_user_post_comment_path(user_id: @post.author.id, post_id: @post.id), class: "comment-link" %></button>
</div>

  </div>
  <p>    <%= @post.text %>
</p>
</div>
      <div class="comment_container">
    <%= render @post.comments %>
  </div>

</div>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>" class="row">
  <% if user.photo.present? && user.photo.attached? %>
    <div class="img">
      <%= image_tag user.photo, alt: "User's profile photo", height: 200, width: 150 %>
    </div>
  <% end %>
  <div class="info">
      <h1><%= link_to user.name, user_path(user) %></h1>
      <p>
        <strong>Number Of Posts:</strong>
        <%= user.postsCounter %>
      </p>
  </div>
</div>

app/views/users/index.html.erb
<div id="users" class="container">
  <% if user_signed_in? %>
    <%= button_to "Sign out", destroy_user_session_path, method: :delete, class: "devise-button" %>
  <% else %>
  <button class="devise-button">
    <%= link_to "Log in", new_user_session_path, class: "link-login"%>
  </button>
  <% end %>

    <% if user_signed_in? %>
    <p class="logged-as">Logged in as <%= current_user.try(:name) %></p>
  <% end %>
        <%= render @users %>
</div>

app/views/users/show.html.erb
<div class="container">
  <%= render @user %>
  <div class="bio">
    <strong>Bio</strong>
    <%= @user.bio %>
  </div>
  <div class="post_container">
    <% @user.recentposts.each do |post| %>
      <div class="post_row">
        <p><%= link_to "#{post.title}", user_post_path(@user.id, post.id) %></p>
        <%= render post %>
      </div>
    <% end %>
  </div>
  <button >
    <%= link_to "See all Posts", user_posts_path(@user), class: "all-posts" %>
  </button>
  <% if current_user.id == @user.id %>
    <button type="button">
      <%= link_to "Create a Post", new_user_post_path(@user), class: "create-post" %>
    </button>
  <% end %>
</div>